env:
  global:
    - CC_TEST_REPORTER_ID=4514488e388611b5f6e624d0476f56773d87fd48248a17b6aa788a1fe21b62cd
language: python
python:
- 3.8
before_install:
- pip install poetry
install:
- poetry install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
- make lint
- poetry run pytest --cov=page_loader tests/ --cov-report xml
fter_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
